name: Deploy Application

on:
  push:
    branches:
      - main # 本番環境

jobs:
  deploy:
    runs-on: ubuntu-latest

    # 本番環境かステージング環境かを条件分岐
    environment: ${{ github.ref_name == 'main' }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Generate .env file
        run: |
          if [[ "${{ github.ref_name }}" == "main" ]]; then
            # 本番環境の .env 生成
            echo "DB_URL=${{ secrets.PROD_TEST_ENV_CONST }}" > .env
          else
            # ステージング環境の .env 生成
            echo "DB_URL=${{ secrets.DEV_TEST_ENV_CONST }}" > .env
          fi
          
      - name: Verify .env file
        run: cat .env # テスト用に内容を出力（実際のプロジェクトでは削除を推奨）
        