name: CD

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy
        uses: appleboy/ssh-action@master #公式か確認
        with:
          host: ${{ secrets.DEPLOY_HOST }}
          username: ${{ secrets.DEPLOY_USER }}
          port: ${{ secrets.DEPLOY_PORT }}
          key: ${{ secrets.DEPLOY_PRIVATE_KEY }}
          script: |
            cd ${{ secrets.DEPLOY_DIR }}
            sudo chown -R $USER:$USER .
            git config --global --add safe.directory "${{ secrets.DEPLOY_DIR }}"
            git pull origin main || echo "Git pull failed. Please check the repository and permissions."
            touch .env
            echo ${{ secrets.PROD_TEST_ENV_CONST}} >> .env
