name: CD

on:
  push:
    branches:
      - feature/*
    paths:
      - '.github/workflows/main.yml'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.DEPLOY_HOST }}
          username: ${{ secrets.DEPLOY_USER }}
          port: ${{ secrets.DEPLOY_PORT }}
          key: ${{ secrets.DEPLOY_PRIVATE_KEY }}
          script: |
            cd ${{ secrets.DEPLOY_DIR }}
            sudo chown -R $USER:$USER .
            git config --global --add safe.directory "${{ secrets.DEPLOY_DIR }}"
            git pull origin main || echo "Git pull failed. Please check the repository and permissions."

  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: test
        run: |
          chmod u+x .github/scripts/test.sh
          .github/scripts/test.sh
