name: CD

on:
  push:
    branches:
      - feature/*
    # 下記に変更があった場合のみ実行
    paths:
      - 'product.php'
      - '.github/workflows/test.yml'
      - '.github/scripts/test01.sh'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      # リポジトリのチェックアウト
      - name: Checkout repository
        uses: actions/checkout@3df4ab11eba7bda6032a0b82a6bb43b11571feac

      # 親ブランチ（main）の最新をフェッチ
      - name: Fetch main branch
        run: git fetch origin

      # 差分の取得
      - name: Get diff with main branch and extract line numbers
        run: |
          # ワークフローを起動したブランチを取得
          branch_name=${{ github.ref }}
          branch_name=${branch_name#refs/heads/}  # refs/heads/ を削除してブランチ名のみ取得

          echo "Branch name: $branch_name"

          # 差分を取得
          git diff --unified=0 origin/main..origin/$branch_name > diff_output.txt
          # 初期化
          current_file=""
          
          # diff と @@ の行を解析
          while IFS= read -r line; do
            # 'diff' 行でファイル名を取得
            if [[ "$line" =~ ^diff ]]; then
              # ファイル名は 'a/ファイル名' と 'b/ファイル名' の形式で出力される
              current_file=$(echo "$line" | sed 's|^diff --git a/\(.*\) b/\1|\1|')
            
            # '@@' 行で変更行番号を取得
            elif [[ "$line" =~ ^@@ ]]; then
              # @@ 行から変更行番号を抽出
              # 例: @@ -10,6 +10,7 @@ なら、10行目から始まり、6行変更
              # 行番号の部分を抽出
              old_line=$(echo "$line" | sed -E 's/^@@ -([0-9]+),.* \+([0-9]+),.*/\1/')
              new_line=$(echo "$line" | sed -E 's/^@@ -.* \+([0-9]+),.*/\1/')
              
              # ファイル名と変更行を表示
              echo "File: $current_file, Old Line: $old_line, New Line: $new_line"
            fi
          done < diff_output.txt


      # PHP をセットアップ
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2' # 必要なPHPバージョンを指定
          extensions: mbstring

      # シェルスクリプトの実行
      - name: Install PHP CodeSniffer and execute
        run: |
          chmod u+x .github/scripts/test01.sh
          .github/scripts/test01.sh "./product.php"
