name: CD

on:
  push:
    branches:
      - feature/*
    # 下記に変更があった場合のみ実行
    paths:
      - 'product.php'
      - '.github/workflows/test.yml'
      - '.github/scripts/*'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      # リポジトリのチェックアウト
      - name: Checkout repository
        uses: actions/checkout@3df4ab11eba7bda6032a0b82a6bb43b11571feac

      # 親ブランチ（main）の最新をフェッチ
      - name: Fetch main branch
        run: git fetch origin

      # 差分の取得
      - name: Get diff with main branch and extract line numbers
        run: |
          chmod u+x .github/scripts/getDiff.sh
          .github/scripts/getDiff.sh ${{ github.ref }}

      # 変更されたファイルを表示（デバッグ用）
      - name: Display modified files
        run: |
          echo "Modified files:"
          echo "${{ env.changed_files }}"

      # PHP をセットアップ
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2' # 必要なPHPバージョンを指定
          extensions: mbstring

      - name: Install PHP CodeSniffer
        run: |
          # phpcsのインストール
          composer global require "squizlabs/php_codesniffer=*"

      # 変更されたファイルに対して PHP_CodeSniffer を実行
      - name: Run PHP CodeSniffer on specific lines
        if: env.changed_files != ''
        run: |
          # 変更ファイル:行を変数に代入
          changed_files="${{ env.changed_files }}"
          # シェルスクリプトに実行権限を付与
          chmod u+x .github/scripts/checkSource.sh
          .github/scripts/checkSource.sh $changed_files
