name: CD

on:
  push:
    branches:
      - feature/*
    # 下記に変更があった場合のみ実行
    paths:
      - './product.php'
      - '.github/workflows/test.yml'
      - '.github/scripts/test01.sh'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      # リポジトリのチェックアウト
      - name: Checkout repository
        uses: actions/checkout@3df4ab11eba7bda6032a0b82a6bb43b11571feac

      # PHP をセットアップ
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2' # 必要なPHPバージョンを指定
          extensions: mbstring

      # シェルスクリプトの実行
      - name: Install PHP CodeSniffer and execute
        run: |
          chmod u+x .github/scripts/test01.sh
          .github/scripts/test01.sh　"./product.php"
