name: CD

on:
  push:
    branches:
      - feature/*
    paths:
      - './product.php'
      - '.github/workflows/test.yml'
      - '.github/scripts/test.yml'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@3df4ab11eba7bda6032a0b82a6bb43b11571feac
      - name: test
        run: |
          chmod u+x .github/scripts/test01.sh
          .github/scripts/test01.sh
